# Generated by Django 6.0.3 on 2026-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='sent_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
